
--NES GAMES
INSERT INTO games VALUES ('The Legend of Zelda', 'NES', 'Nintendo', 1987, 'ZeldaNES.jpg');
INSERT INTO games VALUES ('Ninja Gaiden', 'NES', 'Tecmo', 1988, 'NinjaGaiden.jpg');
INSERT INTO games VALUES ('Batman: The Video Game', 'NES', 'SunSoft', 1989, 'BatmanNES.jpg');
INSERT INTO games VALUES ('Back to the Future', 'NES', 'LJN', 1989, 'BackToTheFuture.jpg');
INSERT INTO games VALUES ('Tecmo NBA Basketball', 'NES', 'Tecmo', 1992, 'TecmoNBA.jpg');
INSERT INTO games VALUES ('Super Mario Bros. / Duck Hunt / World Class Track Meet', 'NES', 'Nintendo', 1990, 'MarioDuckHuntTrack.jpg');
INSERT INTO games VALUES ('Super Mario Bros. 3', 'NES', 'Nintendo', 1990, 'Mario3.jpg');
INSERT INTO games VALUES ('The Three Stooges', 'NES', 'Activision', 1987, 'TheThreeStooges.jpg');

--SNES GAMES
INSERT INTO games VALUES ('Zombies Ate My Neighbors', 'SNES', 'Konami', 1993, 'ZombiesAteMyNeighbors.jpg');
INSERT INTO games VALUES ('Kirby''s Dream Land 3', 'SNES', 'Nintendo', 1997, 'KirbyDreamLand3.jpg');
INSERT INTO games VALUES ('The Legend of Zelda: A Link To The Past', 'SNES', 'Nintendo', 1991, 'LinkToThePast.jpg');
INSERT INTO games VALUES ('The Lion King', 'SNES', 'Virgin Interactive', 1994, 'LionKing.jpg');
INSERT INTO games VALUES ('Radical Psycho Machine Racing', 'SNES', 'Interplay Entertainment', 1991, 'RPMRacing.jpg');
INSERT INTO games VALUES ('Super Mario RPG: Legend of the Seven Stars', 'SNES', 'Nintendo', 1996, 'SuperMarioRPG.jpg');
INSERT INTO games VALUES ('Star Fox', 'SNES', 'Nintendo', 1993, 'StarFox.jpg');
INSERT INTO games VALUES ('Disney''s Goof Troop', 'SNES', 'Capcom', 1993, 'GoofTroop.jpg');
INSERT INTO games VALUES ('ClayFighter', 'SNES', 'Interplay Entertainment', 1993, 'ClayFighter.jpg');
INSERT INTO games VALUES ('Mortal Kombat II', 'SNES', 'Midway Games', 1993, 'MortalKombat2.jpg');
INSERT INTO games VALUES ('Donkey Kong Country', 'SNES', 'Nintendo', 1994, 'DonkeyKongCountry.jpg');
INSERT INTO games VALUES ('Animaniacs', 'SNES', 'Konami', 1994, 'Animaniacs.jpg');
INSERT INTO games VALUES ('Frogger', 'SNES', 'Konami', 1998, 'Frogger.jpg');
INSERT INTO games VALUES ('Super Mario World 2: Yoshi''s Island', 'SNES', 'Nintendo', 1995, 'YoshiIsland.jpg');

--GENESIS GAMES
INSERT INTO games VALUES ('X-Men 2: Clone Wars', 'Genesis', 'Sega', 1995, 'XMenGenesis.jpg');
INSERT INTO games VALUES ('Pac-Man 2: The New Adventures', 'Genesis', 'Namco', 1994, 'PacMan2.jpg');
INSERT INTO games VALUES ('Sonic the Hedgehog 2', 'Genesis', 'Sega', 1992, 'Sonic2.jpg');
INSERT INTO games VALUES ('Eternal Champions', 'Genesis', 'Sega', 1993, 'EternalChampions.jpg');
INSERT INTO games VALUES ('Dr. Robotnik''s Mean Bean Machine', 'Genesis', 'Sega', 1993, 'MeanBeanMachine.jpg');
INSERT INTO games VALUES ('World Series Baseball', 'Genesis', 'Sega', 1993, 'WorldSeriesBaseball.jpg');
INSERT INTO games VALUES ('Spider-Man and Venom: Maximum Carnage', 'Genesis', 'LJN', 1994, 'MaximumCarnage.jpg');

--GAMEBOY GAMES
INSERT INTO games VALUES ('Super Mario Land 2: 6 Golden Coins', 'GameBoy', 'Nintendo', 1992, 'SuperMarioLand2.jpg');
INSERT INTO games VALUES ('Yoshi''s Cookie', 'GameBoy', 'Nintendo', 1992, 'YoshiCookie.jpg');

--N64 Games
INSERT INTO games VALUES ('Turok 2: Seeds of Evil', 'N64', 'Acclaim Entertainment', 1998, 'Turok2.jpg');
INSERT INTO games VALUES ('Turok: Dinosaur Hunter', 'N64', 'Acclaim Entertainment', 1997, 'Turok.jpg');
INSERT INTO games VALUES ('Bomberman Hero', 'N64', 'Nintendo', 1998, 'BombermanHero.jpg');
INSERT INTO games VALUES ('Super Smash Bros.', 'N64', 'Nintendo', 1999, 'SuperSmashBros.jpg');
INSERT INTO games VALUES ('The Legend of Zelda: Majora''s Mask', 'N64', 'Nintendo', 2000, 'MajoraMask.jpg');
INSERT INTO games VALUES ('The Legend of Zelda: Ocarina of Time', 'N64', 'Nintendo', 1998, 'OcarinaOfTime.jpg');
INSERT INTO games VALUES ('Donkey Kong 64', 'N64', 'Nintendo', 1999, 'DonkeyKong64.jpg');
INSERT INTO games VALUES ('Pokémon Stadium', 'N64', 'Nintendo', 1998, 'PokemonStadium.jpg');
INSERT INTO games VALUES ('Super Mario 64', 'N64', 'Nintendo', 1996, 'SuperMario64.jpg');
INSERT INTO games VALUES ('Star Fox 64', 'N64', 'Nintendo', 1997, 'StarFox64.jpg');
INSERT INTO games VALUES ('Banjo-Kazooie', 'N64', 'Rare', 1998, 'BanjoKazooie.jpg');
INSERT INTO games VALUES ('Mario Kart 64', 'N64', 'Nintendo', 1996, 'MarioKart64.jpg');
INSERT INTO games VALUES ('Kirby 64: The Crystal Shards', 'N64', 'Nintendo', 2000, 'Kirby64.jpg');
INSERT INTO games VALUES ('Glover', 'N64', 'Atari', 1999, 'Glover.jpg');
INSERT INTO games VALUES ('Namco Museum', 'N64', 'Namco', 1999, 'NamcoMuseum.jpg');
INSERT INTO games VALUES ('Ms. Pac-Man Maze Madness', 'N64', 'Namco', 2000, 'MsPacMan.jpg');
INSERT INTO games VALUES ('South Park: Chef''s Luv Shack', 'N64', 'Acclaim Entertainment', 1999, 'ChefsLuvShack.jpg');
INSERT INTO games VALUES ('South Park', 'N64', 'Acclaim Entertainment', 1998, 'SouthPark.jpg');
INSERT INTO games VALUES ('Tigger''s Honey Hunt', 'N64', 'Ubisoft', 2000, 'TiggerHoneyHunt.jpg');
INSERT INTO games VALUES ('StarCraft 64', 'N64', 'Blizzard Entertainment', 2000, 'StarCraft64.jpg');
INSERT INTO games VALUES ('Gauntlet Legends', 'N64', 'Midway Games', 1998, 'GauntletLegends.jpg');
INSERT INTO games VALUES ('Mortal Kombat Mythologies: Sub-Zero', 'N64', 'Midway Games', 1997, 'SubZero.jpg');
INSERT INTO games VALUES ('Mortal Kombat 4', 'N64', 'Midway Games', 1997, 'MortalKombat4.jpg');
INSERT INTO games VALUES ('Xena: Warrior Princess: The Talisman of Fate', 'N64', 'Titus Interactive', 1999, 'Xena.jpg');
INSERT INTO games VALUES ('Army Men: Sarge''s Heroes', 'N64', 'The 3DO Company', 1999, 'SargesHeroes.jpg');
INSERT INTO games VALUES ('Duke Nukem 64', 'N64', 'GT Interactive', 1997, 'DukeNukem64.jpg');
INSERT INTO games VALUES ('Quake', 'N64', 'Midway Games', 1996, 'Quake.jpg');
INSERT INTO games VALUES ('Quake II', 'N64', 'Activision', 1997, 'Quake2.jpg');
INSERT INTO games VALUES ('GodenEye 007', 'N64', 'Rare', 1997, 'GoldenEye007.jpg');
INSERT INTO games VALUES ('Diddy Kong Racing', 'N64', 'Rare', 1997, 'DiddyKongRacing.jpg');
INSERT INTO games VALUES ('Army Men: Air Combat', 'N64', 'The 3DO Company', 1999, 'ArmyMenAirCombat.jpg');
INSERT INTO games VALUES ('Pilotwings 64', 'N64', 'Nintendo', 1996, 'PilotWings.jpg');
INSERT INTO games VALUES ('Aero Fighters Assault', 'N64', 'Video System', 1997, 'AeroFightersAssault.jpg');
INSERT INTO games VALUES ('Excitebike 64', 'N64', 'Nintendo', 2000, 'Excitebike64.jpg');
INSERT INTO games VALUES ('Mickey''s Speedway USA', 'N64', 'Rare', 2000, 'MickeySpeedwayUSA.jpg');
INSERT INTO games VALUES ('Star Wars Episode I: Racer', 'N64', 'LucasArts', 1999, 'StarWarsRacer.jpg');
INSERT INTO games VALUES ('Off Road Challenge', 'N64', 'Midway Games', 1997, 'OffRoadChallenge.jpg');
INSERT INTO games VALUES ('Cruis''n World', 'N64', 'Midway Games', 1996, 'CruisinWorld.jpg');
INSERT INTO games VALUES ('Wave Race 64', 'N64', 'Nintendo', 1996, 'WaveRace64.jpg');
INSERT INTO games VALUES ('Bomberman 64', 'N64', 'Hudson Soft', 1997, 'Bomberman64.jpg');
INSERT INTO games VALUES ('Buck Bumble', 'N64', 'Ubisoft', 1998, 'BuckBumble.jpg');
INSERT INTO games VALUES ('Blast Corps', 'N64', 'Rare', 1997, 'BlastCorps.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Rainbow Six', 'N64', 'Red Storm Entertainment', 1998, 'RainbowSixN64.jpg');
INSERT INTO games VALUES ('FIFA 99', 'N64', 'Electronic Arts', 1998, 'Fifa99.jpg');
INSERT INTO games VALUES ('Wayne Gretzky''s 3D Hockey', 'N64', 'Midway Games', 1996, 'WayneGretzky.jpg');
INSERT INTO games VALUES ('Major League Baseball Featuring Ken Griffey Jr.', 'N64', 'Nintendo', 1998, 'KenGriffeyJr.jpg');
INSERT INTO games VALUES ('NFL Blitz 2000', 'N64', 'Midway Games', 1999, 'Blitz2000.jpg');
INSERT INTO games VALUES ('All-Star Baseball 2001', 'N64', 'Acclaim Games', 2000, 'AllStarBaseball2001.jpg');
INSERT INTO games VALUES ('Madden NFL 2001', 'N64', 'Electronic Arts', 2000, 'Madden2001.jpg');
INSERT INTO games VALUES ('Kobe Bryant in NBA Courtside', 'N64', 'Left Field Productions', 1998, 'NBACourtside.jpg');
INSERT INTO games VALUES ('NBA Live 99', 'N64', 'Electronic Arts', 1998, 'NBALive99.jpg');
INSERT INTO games VALUES ('NHL 99', 'N64', 'Electronic Arts', 1998, 'NHL99.jpg');
INSERT INTO games VALUES ('Gex 3: Deep Cover Gecko', 'N64', 'Crave Entertainment', 1999, 'Gex3.jpg');
INSERT INTO games VALUES ('Jet Force Gemini', 'N64', 'Rare', 1999, 'JetForceGemini.jpg');
INSERT INTO games VALUES ('Perfect Dark', 'N64', 'Rare', 2000, 'PerfectDark.jpg');
INSERT INTO games VALUES ('Star Wars: Shadows of the Empire', 'N64', 'LucasArts', 1996, 'ShadowsOfTheEmpire.jpg');
INSERT INTO games VALUES ('Ready 2 Rumble Boxing', 'N64', 'Midway Games', 1999, 'Ready2Rumble.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Pro Skater', 'N64', 'Activision', 1999, 'TonyHawk.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Pro Skater 2', 'N64', 'Activision', 2000, 'TonyHawk2.jpg');
INSERT INTO games VALUES ('1080° Snowboarding', 'N64', 'Nintendo', 1998, '1080.jpg');
INSERT INTO games VALUES ('WWF WrestleMania 2000', 'N64', 'THQ', 1999, 'Wrestlemania2000.jpg');
INSERT INTO games VALUES ('WWF No Mercy', 'N64', 'THQ', 2000, 'NoMercy.jpg');
INSERT INTO games VALUES ('WWF War Zone', 'N64', 'Acclaim Entertainment', 1998, 'WarZone.jpg');
INSERT INTO games VALUES ('WCW/nWo Revenge', 'N64', 'THQ', 1998, 'WCWNWORevenge.jpg');
INSERT INTO games VALUES ('Pokemon Snap', 'N64', 'Nintendo', 1999, 'PokemonSnap.jpg');
INSERT INTO games VALUES ('F-1 World Grand Prix', 'N64', 'Video System', 1998, 'F1.jpg');
INSERT INTO games VALUES ('Tonic Trouble', 'N64', 'Ubisoft', 1999, 'TonicTrouble.jpg');
INSERT INTO games VALUES ('007: The World Is Not Enough', 'N64', 'Electronic Arts', 2000, 'WorldIsnotEnough.jpg');
INSERT INTO games VALUES ('Bio F.R.E.A.K.S.', 'N64', 'Midway Games', 1998, 'BioFreaks.jpg');
INSERT INTO games VALUES ('Dark Rift', 'N64', 'Tokai Communications', 1997, 'DarkRift.jpg');
INSERT INTO games VALUES ('Mace: The Dark Age', 'N64', 'Midway Games', 1997, 'Mace.jpg');
INSERT INTO games VALUES ('Mission: Impossible', 'N64', 'Infogrames Entertainment', 1998, 'MissionImpossible.jpg');
INSERT INTO games VALUES ('Shadow Man', 'N64', 'Acclaim Entertainment', 1999, 'ShadowMan.jpg');
INSERT INTO games VALUES ('S.C.A.R.S.', 'N64', 'Ubisoft', 1998, 'Scars.jpg');
INSERT INTO games VALUES ('Rugrats: Scavenger Hunt', 'N64', 'THQ', 1999, 'RugratsScavengerHunt.jpg');
INSERT INTO games VALUES ('War Gods', 'N64', 'Midway Games', 1995, 'WarGods.jpg');
INSERT INTO games VALUES ('Hexen Beyond Heretic', 'N64', 'id Software', 1995, 'Hexen.jpg');
INSERT INTO games VALUES ('Flying Dragon', 'N64', 'Culture Brain', 1998, 'FlyingDragon.jpg');
INSERT INTO games VALUES ('Knife Edge: Nose Gunner', 'N64', 'Kemco', 1998, 'KnifeEdge.jpg');

--PLAYSTATION GAMES
INSERT INTO games VALUES ('Metal Gear Solid', 'PS1', 'Konami', 1998, 'MetalGearSolid.jpg');
INSERT INTO games VALUES ('Chrono Cross', 'PS1', 'Square', 1999, 'ChronoCross.jpg');
INSERT INTO games VALUES ('Colony Wars III: Red Sun', 'PS1', 'Psygnosis', 2000, 'ColonyWarsIII.jpg');
INSERT INTO games VALUES ('Dragon Ball Z: Ultimate Battle 22', 'PS1', 'Bandai', 1995, 'UltimateBattle22.jpg');
INSERT INTO games VALUES ('Final Fantasy Tactics', 'PS1', 'Square', 1998, 'FinalFantasyTactics.jpg');
INSERT INTO games VALUES ('Final Fantasy VII', 'PS1', 'Square', 1997, 'FinalFantasyVII.jpg');
INSERT INTO games VALUES ('Forsaken', 'PS1', 'Acclaim Entertainment', 1998, 'Forsaken.jpg');
INSERT INTO games VALUES ('Twisted Metal III', 'PS1', '989 Studios', 1998, 'TwistedMetalIII.jpg');

--GAMEBOY ADVANCE GAMES
INSERT INTO games VALUES ('Final Fantasy Tactics Advance', 'GBA', 'Square', 2003, 'TacticsAdvance.jpg');
INSERT INTO games VALUES ('Sword of Mana', 'GBA', 'Square Enix', 2003, 'SwordOfMana.jpg');
INSERT INTO games VALUES ('Finding Nemo', 'GBA', 'THQ', 2003, 'FindingNemo.jpg');

--PLAYSTATION 2 GAMES
INSERT INTO games VALUES ('Deus Ex: The Conspiracy', 'PS2', 'Eidos Interactive', 2000, 'DeusEx.jpg');
INSERT INTO games VALUES ('Odin Sphere', 'PS2', 'Atlus', 2007, 'OdinSphere.jpg');
INSERT INTO games VALUES ('One Piece: Pirates'' Carnival', 'PS2', 'Bandai', 2005, 'PirateCarnival.jpg');
INSERT INTO games VALUES ('Pride FC: Fighting Championships', 'PS2', 'THQ', 2003, 'PrideFC.jpg');
INSERT INTO games VALUES ('Final Fantasy XII', 'PS2', 'Square Enix', 2006, 'FinalFantasyXII.jpg');
INSERT INTO games VALUES ('Metal Gear Solid 2: Sons of Liberty', 'PS2', 'Konami', 2001, 'MetalGearSolid2.jpg');
INSERT INTO games VALUES ('Unreal Tournament', 'PS2', 'Epic Games', 2001, 'UnrealTournament.jpg');
INSERT INTO games VALUES ('Lupin the 3rd: Treasure of the Sorcerer King', 'PS2', 'Bandai', 2002, 'LupinThe3rd.jpg');
INSERT INTO games VALUES ('Naruto: Uzumaki Chronicles', 'PS2', 'Bandai', 2005, 'UzumakiChronicles.jpg');
INSERT INTO games VALUES ('Backyard Wrestling: Don''t Try This at Home', 'PS2', 'Midway Games', 2003, 'BackyardWrestling.jpg');
INSERT INTO games VALUES ('Freestyle Metal X', 'PS2', 'Midway Games', 2003, 'FreestyleMetalX.jpg');
INSERT INTO games VALUES ('Pirates of the Caribbean: At World''s End', 'PS2', 'Disney Interactive Studios', 2007, 'AtWorldsEnd.jpg');
INSERT INTO games VALUES ('Pirates: Legend of the Black Buccaneer', 'PS2', 'Valcon Games', 2006, 'BlackBuccaneer.jpg');
INSERT INTO games VALUES ('Barbarian', 'PS2', 'Titus Interactive', 2002, 'Barbarian.jpg');
INSERT INTO games VALUES ('World Destruction League: Thunder Tanks', 'PS2', 'The 3DO Company', 2000, 'ThunderTanks.jpg');
INSERT INTO games VALUES ('The Nightmare of Druaga: Fushigi no Dungeon', 'PS2', 'Namco', 2004, 'NightmareOfDruaga.jpg');
INSERT INTO games VALUES ('Evergrace', 'PS2', 'FromSoftware', 2000, 'Evergrace.jpg');

--GAMECUBE GAMES
INSERT INTO games VALUES ('Final Fantasy Crystal Chronicles', 'GameCube', 'Square Enix', 2003, 'CrystalChronicles.jpg');
INSERT INTO games VALUES ('Super Smash Bros. Melee', 'GameCube', 'Nintendo', 2001, 'Melee.jpg');
INSERT INTO games VALUES ('Def Jam Vendetta', 'GameCube', 'Electronic Arts', 2003, 'DefJamVendetta.jpg');
INSERT INTO games VALUES ('WWE WrestleMania X8', 'GameCube', 'THQ', 2002, 'Wrestlemania18.jpg');
INSERT INTO games VALUES ('Sonic Mega Collection', 'GameCube', 'Sega', 2002, 'SonicMegaCollection.jpg');
INSERT INTO games VALUES ('Billy Hatcher and the Giant Egg', 'GameCube', 'Sega', 2003, 'BillyHatcher.jpg');
INSERT INTO games VALUES ('Disney''s PK: Out of the Shadows', 'GameCube', 'Ubisoft', 2002, 'PK.jpg');
INSERT INTO games VALUES ('Cars', 'GameCube', 'THQ', 2006, 'Cars.jpg');
INSERT INTO games VALUES ('The Incredibles: Rise of the Underminer', 'GameCube', 'THQ', 2005, 'Incredibles2.jpg');
INSERT INTO games VALUES ('The Legend of Spyro: A New Beginning', 'GameCube', 'Sierra Entertainment', 2006, 'SpyroNewBeginning.jpg');
INSERT INTO games VALUES ('The Legend of Zelda: The Wind Waker', 'GameCube', 'Nintendo', 2002, 'WindWaker.jpg');
INSERT INTO games VALUES ('Mario Golf: Toadstool Tour', 'GameCube', 'Nintendo', 2003, 'ToadstoolTour.jpg');
INSERT INTO games VALUES ('Metal Arms: Glitch in the System', 'GameCube', 'Sierra Entertainment', 2003, 'MetalArms.jpg');
INSERT INTO games VALUES ('Metroid Prime', 'GameCube', 'Nintendo', 2002, 'MetroidPrime.jpg');
INSERT INTO games VALUES ('Paper Mario: The Thousand-Year Door', 'GameCube', 'Nintendo', 2004, 'ThousandYearDoor.jpg');
INSERT INTO games VALUES ('Rampage: Total Destruction', 'GameCube', 'Midway Games', 2006, 'TotalDestruction.jpg');
INSERT INTO games VALUES ('Lego Star Wars: The Video Game', 'GameCube', 'LucasArts', 2005, 'LegoStarWars.jpg');
INSERT INTO games VALUES ('Lego Star Wars II: The Original Trilogy', 'GameCube', 'LucasArts', 2006, 'LegoStarWars2.jpg');

--XBOX GAMES
INSERT INTO games VALUES ('Kung Fu Chaos', 'Xbox', 'Microsoft Studios', 2003, 'KungFuChaos.jpg');
INSERT INTO games VALUES ('Mortal Kombat: Deadly Alliance', 'Xbox', 'Midway Games', 2002, 'DeadlyAlliance.jpg');
INSERT INTO games VALUES ('Circus Maximus: Chariot Wars', 'Xbox', 'THQ', 2002, 'ChariotWars.jpg');
INSERT INTO games VALUES ('Sega GT 2002', 'Xbox', 'Sega', 2002, 'SegaGT.jpg');
INSERT INTO games VALUES ('Jet Set Radio Future', 'Xbox', 'Sega', 2002, 'JetSetRadioFuture.jpg');
INSERT INTO games VALUES ('Soul Calibur II', 'Xbox', 'Namco', 2002, 'SoulCaliburXbox.jpg');
INSERT INTO games VALUES ('Enclave', 'Xbox', 'Conspiracy Entertainment', 2002, 'Enclave.jpg');
INSERT INTO games VALUES ('Black Stone: Magic & Steel', 'Xbox', 'Xicat Interactive', 2003, 'BlackStone.jpg');
INSERT INTO games VALUES ('Brute Force', 'Xbox', 'Microsoft Studios', 2003, 'BruteForce.jpg');
INSERT INTO games VALUES ('The Chronicles of Riddick: Escape From Butcher Bay', 'Xbox', 'Vivendi Games', 2004, 'ButcherBay.jpg');
INSERT INTO games VALUES ('Conker: Live & Reloaded', 'Xbox', 'Rare', 2005, 'LiveAndReloaded.jpg');
INSERT INTO games VALUES ('Crimson Skies: High Road to Revenge', 'Xbox', 'Microsoft Studios', 2003, 'CrimsonSkies.jpg');
INSERT INTO games VALUES ('Dead Or Alive Ultimate 2', 'Xbox', 'Tecmo', 2004, 'DeadOrAlive2.jpg');
INSERT INTO games VALUES ('Dead Or Alive 3', 'Xbox', 'Tecmo', 2001, 'DeadOrAlive3.jpg');
INSERT INTO games VALUES ('Dead Or Alive Ultimate', 'Xbox', 'Tecmo', 2004, 'DeadOrAliveUltimate.jpg');
INSERT INTO games VALUES ('Dead Or Alive Xtreme Beach Volleyball', 'Xbox', 'Tecmo', 2003, 'XtremeBeachVolleyball.jpg');
INSERT INTO games VALUES ('Destroy All Humans!', 'Xbox', 'THQ', 2005, 'DestroyAllHumans.jpg');
INSERT INTO games VALUES ('Doom 3', 'Xbox', 'Activision', 2004, 'Doom3.jpg');
INSERT INTO games VALUES ('The Elder Scrolls III: Morrowind', 'Xbox', 'Bethesda Softworks', 2002, 'Morrowind.jpg');
INSERT INTO games VALUES ('Enter the Matrix', 'Xbox', 'Atari', 2003, 'EnterTheMatrix.jpg');
INSERT INTO games VALUES ('James Bond 007: Everything or Nothing', 'Xbox', 'Electronic Arts', 2003, 'EverythingOrNothing.jpg');
INSERT INTO games VALUES ('Fable', 'Xbox', 'Lionhead Studios', 2004, 'Fable.jpg');
INSERT INTO games VALUES ('Far Cry Instincts: Evolution', 'Xbox', 'Ubisoft', 2005, 'FarCryEvolution.jpg');
INSERT INTO games VALUES ('FlatOut', 'Xbox', 'Empire Interactive', 2005, 'FlatOut.jpg');
INSERT INTO games VALUES ('James Bond 007: From Russia With Love', 'Xbox', 'Electronic Arts', 2005, 'RussiaWithLove.jpg');
INSERT INTO games VALUES ('Future Tactics: The Uprising', 'Xbox', 'Crave Entertainment', 2004, 'FutureTactics.jpg');
INSERT INTO games VALUES ('Fuzion Frenzy', 'Xbox', 'Microsoft Studios', 2001, 'FuzionFrenzy.jpg');
INSERT INTO games VALUES ('Gauntlet: Seven Sorrows', 'Xbox', 'Midway Games', 2005, 'SevenSorrows.jpg');
INSERT INTO games VALUES ('Goblin Commander: Unleash the Horde', 'Xbox', 'Jaleco', 2003, 'GoblinCommander.jpg');
INSERT INTO games VALUES ('Ninja Gaiden', 'Xbox', 'Tecmo', 2004, 'NinjaGaidenXbox.jpg');
INSERT INTO games VALUES ('Worms 3D', 'Xbox', 'Team17', 2003, 'Worms3D.jpg');
INSERT INTO games VALUES ('Worms Forts: Under Siege', 'Xbox', 'Team 17', 2004, 'WormsForts.jpg');
INSERT INTO games VALUES ('Blood Omen 2', 'Xbox', 'Eidos Interactive', 2002, 'BloodOmen2.jpg');
INSERT INTO games VALUES ('Burnout 3: Takedown', 'Xbox', 'Electronic Arts', 2004, 'Burnout3.jpg');
INSERT INTO games VALUES ('Big Mutha Truckers', 'Xbox', 'THQ', 2002, 'MuthaTruckers.jpg');
INSERT INTO games VALUES ('Raze''s Hell', 'Xbox', 'Majesco Entertainment', 2005, 'RazeHell.jpg');
INSERT INTO games VALUES ('The Lord of the Rings: The Fellowship of the Ring', 'Xbox', 'Vivendi Games', 2002, 'FellowshipXbox.jpg');
INSERT INTO games VALUES ('The Lord of the Rings: The Two Towers', 'Xbox', 'Electronic Arts', 2002, 'TwoTowersXbox.jpg');
INSERT INTO games VALUES ('Max Payne', 'Xbox', 'Remedy Entertainment', 2001, 'MaxPayne.jpg');
INSERT INTO games VALUES ('MechAssault 2: Lone Wolf', 'Xbox', 'Microsoft Studios', 2004, 'MechAssault2.jpg');
INSERT INTO games VALUES ('MechAssault', 'Xbox', 'Microsoft Studios', 2002, 'MechAssault.jpg');
INSERT INTO games VALUES ('Marvel Nemesis: Rise of the Imperfects', 'Xbox', 'Electronic Arts', 2005, 'MarvelNemesis.jpg');
INSERT INTO games VALUES ('Phantasy Star Online Episode I & II', 'Xbox', 'Sega', 2002, 'PhantasyStar.jpg');
INSERT INTO games VALUES ('Oddworld: Munch''s Oddysee', 'Xbox', 'Oddworld Inhabitants', 2001, 'OddworldMunch.jpg');
INSERT INTO games VALUES ('Midway Arcade Treasures', 'Xbox', 'Midway Games', 2003, 'ArcadeTreasures.jpg');
INSERT INTO games VALUES ('Max Payne 2: The Fall of Max Payne', 'Xbox', 'Rockstar Games', 2003, 'MaxPayne2.jpg');
INSERT INTO games VALUES ('Outlaw Golf', 'Xbox', 'Global Star Software', 2002, 'OutlawGolf.jpg');
INSERT INTO games VALUES ('Outlaw Golf 2', 'Xbox', 'Global Star Software', 2002, 'OutlawGolf2.jpg');
INSERT INTO games VALUES ('Outlaw Golf: 9 Holes of X-Mas', 'Xbox', 'Hypnotix', 2002, '9Holes.jpg');
INSERT INTO games VALUES ('Outlaw Golf: 9 More Holes of X-Mas', 'Xbox', 'Hypnotix', 2003, '9MoreHoles.jpg');
INSERT INTO games VALUES ('Pariah', 'Xbox', 'Groove Games', 2005, 'Pariah.jpg');
INSERT INTO games VALUES ('Prince of Persia: The Sands of Time', 'Xbox', 'Ubisoft', 2003, 'SandsOfTime.jpg');
INSERT INTO games VALUES ('Spawn: Armageddon', 'Xbox', 'Namco', 2003, 'SpawnArmageddon.jpg');
INSERT INTO games VALUES ('Spider-Man 2', 'Xbox', 'Activision', 2004, 'SpiderMan2Xbox.jpg');
INSERT INTO games VALUES ('Tenchu: Return From Darkness', 'Xbox', 'Activision', 2004, 'ReturnFromDarkness.jpg');
INSERT INTO games VALUES ('Dungeons & Dragons: Heroes', 'Xbox', 'Atari', 2003, 'DungeonHeroes.jpg');
INSERT INTO games VALUES ('Halo 2', 'Xbox', 'Bungie', 2004, 'Halo2.jpg');
INSERT INTO games VALUES ('Halo 2: Multiplayer Map Pack', 'Xbox', 'Bungie', 2005, 'MultiplayerMapPack.jpg');
INSERT INTO games VALUES ('GoldenEye: Rogue Agent', 'Xbox', 'Electronic Arts', 2004, 'RogueAgent.jpg');
INSERT INTO games VALUES ('Counter-Strike', 'Xbox', 'Valve Corporation', 2003, 'CounterStrike.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Ghost Recon 2', 'Xbox', 'Ubisoft', 2004, 'GhostRecon2.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Ghost Recon', 'Xbox', 'Ubisoft', 2002, 'GhostRecon.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Ghost Recon Advanced Warfighter', 'Xbox', 'Ubisoft', 2006, 'AdvancedWarfighter.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Ghost Recon: Island Thunder', 'Xbox', 'Ubisoft', 2002, 'IslandThunder.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Rainbow Six: Lockdown', 'Xbox', 'Ubisoft', 2005, 'RainbowSixLockdown.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Rainbow Six 3', 'Xbox', 'Ubisoft', 2003, 'RainbowSix3.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Rainbow Six 3: Black Arrow', 'Xbox', 'Ubisoft', 2004, 'BlackArrow.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Splinter Cell: Pandora Tomorrow', 'Xbox', 'Ubisoft', 2004, 'PandoraTomorrow.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Splinter Cell', 'Xbox', 'Ubisoft', 2002, 'SplinterCell.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Splinter Cell: Chaos Theory', 'Xbox', 'Ubisoft', 2005, 'ChaosTheory.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Pro Skater 2x', 'Xbox', 'Activision', 2001, 'TonyHawk2x.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Pro Skater 4', 'Xbox', 'Activision', 2002, 'TonyHawk4.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Underground', 'Xbox', 'Activision', 2003, 'Underground.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Underground 2', 'Xbox', 'Activision', 2004, 'Underground2.jpg');
INSERT INTO games VALUES ('Tony Hawk''s American Wasteland', 'Xbox', 'Activision', 2005, 'AmericanWasteland.jpg');
INSERT INTO games VALUES ('Tony Hawk''s Project 8', 'Xbox', 'Activision', 2006, 'Project8.jpg');
INSERT INTO games VALUES ('True Crime: New York City', 'Xbox', 'Activision', 2005, 'TrueCrimeNYC.jpg');
INSERT INTO games VALUES ('Unreal II: The Awakening', 'Xbox', 'Atari', 2003, 'UnrealII.jpg');
INSERT INTO games VALUES ('Unreal Championship', 'Xbox', 'Atari', 2002, 'UnrealChampionship.jpg');
INSERT INTO games VALUES ('Unreal Championship 2: The Liandri Conflict', 'Xbox', 'Midway Games', 2005, 'LiandriConflict.jpg');
INSERT INTO games VALUES ('X-Men Legends II: Rise of Apocalypse', 'Xbox', 'Activision', 2005, 'RiseOfApocalypse.jpg');
INSERT INTO games VALUES ('X-Men: Next Dimension', 'Xbox', 'Activision', 2002, 'NextDimension.jpg');
INSERT INTO games VALUES ('The Warriors', 'Xbox', 'Rockstar Games', 2005, 'Warriors.jpg');

--DREAMCAST GAMES
INSERT INTO games VALUES ('Sonic Adventure', 'Dreamcast', 'Sega', 1998, 'SonicAdventure.jpg');
INSERT INTO games VALUES ('Jet Grind Radio', 'Dreamcast', 'Sega', 2000, 'JetGrindRadio.jpg');

--WII GAMES
INSERT INTO games VALUES ('One Piece: Unlimited Adventure', 'Wii', 'Bandai Namco', 2008, 'UnlimitedAdventure.jpg');
INSERT INTO games VALUES ('Ōkami', 'Wii', 'Capcom', 2006, 'Okami.jpg');
INSERT INTO games VALUES ('Metroid Prime 3: Corruption', 'Wii', 'Nintendo', 2007, 'MetroidCorruption.jpg');
INSERT INTO games VALUES ('Star Wars: The Force Unleashed II', 'Wii', 'LucasArts', 2010, 'ForceUnleashed2.jpg');
INSERT INTO games VALUES ('Nights: Journey of Dreams', 'Wii', 'Sega', 2007, 'JourneyOfDreams.jpg');
INSERT INTO games VALUES ('The Legend of Zelda: Twilight Princess', 'Wii', 'Nintendo', 2006, 'TwilightPrincess.jpg');
INSERT INTO games VALUES ('Fortune Street', 'Wii', 'Nintendo', 2011, 'FortuneStreet.jpg');
INSERT INTO games VALUES ('Worms: A Space Oddity', 'Wii', 'Team17', 2008, 'SpaceOddity.jpg');
INSERT INTO games VALUES ('The Conduit', 'Wii', 'Sega', 2009, 'TheConduit.jpg');
INSERT INTO games VALUES ('Wario Land: Shake It!', 'Wii', 'Nintendo', 2008, 'WarioShakeIt.jpg');

--NINTENDO DS GAMES
INSERT INTO games VALUES ('Radiant Historia', 'DS', 'Atlus', 2011, 'RadiantHistoria.jpg');
INSERT INTO games VALUES ('Chrono Trigger', 'DS', 'Square', 2008, 'ChronoTriggerDS.jpg');
INSERT INTO games VALUES ('Final Fantasy Tactics A2: Grimoire of the Rift', 'DS', 'Square Enix', 2007, 'TacticsA2.jpg');
INSERT INTO games VALUES ('Final Fantasy III', 'DS', 'Square Enix', 2006, 'FinalFantasy3.jpg');
INSERT INTO games VALUES ('Super Princess Peach', 'DS', 'Nintendo', 2005, 'SuperPeach.jpg');
INSERT INTO games VALUES ('The Lord of the Rings: Aragorn''s Quest', 'DS', 'Warner Bros. Interactive Entertainment', 2010, 'AragornQuest.jpg');

--PLAYSTATION 3 GAMES
INSERT INTO games VALUES ('Ultimate Marvel vs. Capcom 3', 'PS3', 'Capcom', 2011, 'MarvelCapcom3.jpg');
INSERT INTO games VALUES ('Marvel: Ultimate Alliance', 'PS3', 'Activision', 2006, 'UltimateAlliance.jpg');
INSERT INTO games VALUES ('Marvel: Ultimate Alliance 2', 'PS3', 'Activision', 2009, 'UltimateAlliance2.jpg');
INSERT INTO games VALUES ('Yakuza: Dead Souls', 'PS3', 'Sega', 2011, 'YakuzaDeadSouls.jpg');
INSERT INTO games VALUES ('Sniper Elite V2 Silver Star Edition', 'PS3', '505 Games', 2012, 'SniperSilverStar.jpg');
INSERT INTO games VALUES ('Ninja Gaiden Sigma 2', 'PS3', 'Team Ninja', 2009, 'NinjaGaidenSigma2.jpg');
INSERT INTO games VALUES ('Soul Calibur IV', 'PS3', 'Bandai Namco', 2008, 'SoulCalibur4.jpg');
INSERT INTO games VALUES ('Borderlands: The Pre-Sequel!', 'PS3', 'Gearbox Software', 2014, 'PreSequel.jpg');
INSERT INTO games VALUES ('The Evil Within', 'PS3', 'Bethesda Softworks', 2014, 'EvilWithin.jpg');
INSERT INTO games VALUES ('Sly Cooper: Thieves in Time', 'PS3', 'Sanzaru Games', 2013, 'ThievesInTime.jpg');
INSERT INTO games VALUES ('L.A.Noire', 'PS3', 'Rockstar Games', 2011, 'LANoire.jpg');
INSERT INTO games VALUES ('Red Dead Redemption', 'PS3', 'Rockstar Games', 2010, 'RedDeadRedemption.jpg');
INSERT INTO games VALUES ('Midnight Club: Los Angeles Complete Edition', 'PS3', 'Rockstar Games', 2008, 'MidnightClubLA.jpg');
INSERT INTO games VALUES ('Grand Theft Auto: Episodes From Liberty City', 'PS3', 'Rockstar Games', 2010, 'GTALiberty.jpg');
INSERT INTO games VALUES ('Dead Space 3 Limited Edition', 'PS3', 'Electronic Arts', 2013, 'DeadSpace3.jpg');
INSERT INTO games VALUES ('Final Fantasy XIII-2', 'PS3', 'Square Enix', 2011, 'FFXIII2.jpg');
INSERT INTO games VALUES ('Red Faction: Armageddon', 'PS3', 'THQ', 2011, 'RedFactionArmageddon.jpg');
INSERT INTO games VALUES ('Spec Ops: The Line', 'PS3', '2K Games', 2012, 'SpecOpsLine.jpg');
INSERT INTO games VALUES ('Kingdom Hearts HD 1.5 ReMIX', 'PS3', 'Square Enix', 2013, 'KingdomHeartsRemix.jpg');
INSERT INTO games VALUES ('Dragon Ball Z: Battle of Z', 'PS3', 'Bandai Namco', 2014, 'BattleOfZ.jpg');
INSERT INTO games VALUES ('Final Fantasy X/X-2 HD Remaster', 'PS3', 'Square Enix', 2013, 'FFXRemaster.jpg');
INSERT INTO games VALUES ('Tekken Hybrid', 'PS3', 'Namco', 2011, 'TekkenHybrid.jpg');
INSERT INTO games VALUES ('Max Payne 3', 'PS3', 'Rockstar Games', 2012, 'MaxPayne3.jpg');
INSERT INTO games VALUES ('Grand Theft Auto IV', 'PS3', 'Rockstar Games', 2008, 'GrandTheftAutoIV.jpg');
INSERT INTO games VALUES ('Dynasty Warriors: Gundam 3', 'PS3', 'Bandai Namco', 2010, 'DynastyGundam.jpg');
INSERT INTO games VALUES ('Injustice: Gods Among Us', 'PS3', 'NetherRealm Studios', 2013, 'Injustice.jpg');
INSERT INTO games VALUES ('Metal Gear Solid 4: Guns of the Patriots', 'PS3', 'Konami', 2008, 'MetalGearSolid4.jpg');
INSERT INTO games VALUES ('Zone of the Enders HD Collection', 'PS3', 'Konami', 2012, 'EndersHD.jpg');

--XBOX 360 GAMES
INSERT INTO games VALUES ('Deus Ex: Human Revolution', '360', 'Square Enix', 2011, 'HumanRevolution.jpg');
INSERT INTO games VALUES ('Mass Effect Trilogy', '360', 'Electronic Arts', 2012, 'MassEffectTrilogy.jpg');
INSERT INTO games VALUES ('Halo 3', '360', 'Bungie', 2007, 'Halo3.jpg');
INSERT INTO games VALUES ('Gears of War: Judgment', '360', 'Epic Games', 2013, 'GoWJudgment.jpg');
INSERT INTO games VALUES ('Far Cry 3', '360', 'Ubisoft', 2012, 'FarCry3.jpg');
INSERT INTO games VALUES ('Far Cry Instincts: Predator', '360', 'Ubisoft', 2005, 'FarCryPredator.jpg');
INSERT INTO games VALUES ('Halo: Combat Evolved Anniversary', '360', '343 Industries', 2011, 'HaloAnniversary.jpg');
INSERT INTO games VALUES ('Metal Gear Solid HD Collection', '360', 'Konami', 2011, 'MetalGearCollection.jpg');
INSERT INTO games VALUES ('Bulletstorm Epic Edition', '360', 'Electronic Arts', 2011, 'Bulletstorm.jpg');
INSERT INTO games VALUES ('Bayonetta', '360', 'Platinum Games', 2009, 'Bayonetta.jpg');
INSERT INTO games VALUES ('Assassin''s Creed II', '360', 'Ubisoft', 2009, 'AssassinsCreed2.jpg');
INSERT INTO games VALUES ('Assassin''s Creed: Brotherhood', '360', 'Ubisoft', 2010, 'AssassinsCreedBrotherhood.jpg');
INSERT INTO games VALUES ('Assassin''s Creed: Revelations', '360', 'Ubisoft', 2011, 'AssassinsRevelations.jpg');
INSERT INTO games VALUES ('Assassin''s Creed III', '360', 'Ubisoft', 2012, 'AssassinsCreed3.jpg');
INSERT INTO games VALUES ('Assassin''s Creed IV: Black Flag', '360', 'Ubisoft', 2013, 'BlackFlag.jpg');
INSERT INTO games VALUES ('Batman: Arkham Asylum', '360', 'Warner Bros. Interactive', 2009, 'ArkhamAsylum.jpg');
INSERT INTO games VALUES ('Batman: Arkham City', '360', 'Warner Bros. Interactive', 2011, 'ArkhamCity.jpg');
INSERT INTO games VALUES ('Borderlands', '360', 'Gearbox Software', 2009, 'Borderlands.jpg');
INSERT INTO games VALUES ('Castlevania: Lords of Shadow', '360', 'Konami', 2010, 'LordsOfShadow.jpg');
INSERT INTO games VALUES ('Dante''s Inferno', '360', 'Electronic Arts', 2010, 'DanteInferno.jpg');
INSERT INTO games VALUES ('Darksiders', '360', 'THQ', 2010, 'Darksiders.jpg');
INSERT INTO games VALUES ('Dark Souls', '360', 'FromSoftware', 2011, 'DarkSouls.jpg');
INSERT INTO games VALUES ('Dishonored', '360', 'Bethesda Softworks', 2012, 'Dishonored.jpg');
INSERT INTO games VALUES ('Duke Nukem Forever', '360', '2K Games', 2011, 'DukeNukemForever.jpg');
INSERT INTO games VALUES ('The Elder Scrolls IV: Oblivion', '360', 'Bethesda Softworks', 2006, 'Oblivion.jpg');
INSERT INTO games VALUES ('The Elder Scrolls IV: Shivering Isles', '360', 'Bethesda Softworks', 2007, 'ShiveringIsles.jpg');
INSERT INTO games VALUES ('The Elder Scrolls V: Skyrim', '360', 'Bethesda Softworks', 2011, 'Skyrim.jpg');
INSERT INTO games VALUES ('Fable III', '360', 'Lionhead Studios', 2010, 'Fable3.jpg');
INSERT INTO games VALUES ('F.E.A.R. 2: Project Origin', '360', 'Monolith Productions', 2009, 'Fear2.jpg');
INSERT INTO games VALUES ('F.E.A.R. 3', '360', 'Warner Bros. Interactive Entertainment', 2011, 'Fear3.jpg');
INSERT INTO games VALUES ('Game of Thrones', '360', 'Atlus', 2012, 'GameOfThronesRPG.jpg');
INSERT INTO games VALUES ('Gears of War 2', '360', 'Epic Games', 2008, 'GoW2.jpg');
INSERT INTO games VALUES ('Gears of War', '360', 'Epic Games', 2006, 'GoW.jpg');
INSERT INTO games VALUES ('Red Dead Redemption', '360', 'Rockstar Games', 2010, 'RedDead360.jpg');
INSERT INTO games VALUES ('Gears of War 3', '360', 'Epic Games', 2011, 'GoW3.jpg');
INSERT INTO games VALUES ('Disney Infinity', '360', 'Disney Interactive Studios', 2013, 'DisneyInfinity.jpg');
INSERT INTO games VALUES ('Record of Agarest War Zero', '360', 'Aksys Games', 2009, 'AgarestWar.jpg');
INSERT INTO games VALUES ('Enemy Territory: Quake Wars', '360', 'id Software', 2007, 'QuakeWars.jpg');
INSERT INTO games VALUES ('DmC: Devil May Cry', '360', 'Capcom', 2013, 'DMC.jpg');
INSERT INTO games VALUES ('GoldenEye 007: Reloaded', '360', 'Activision', 2010, 'GoldeneyeReloaded.jpg');
INSERT INTO games VALUES ('Guitar Hero III: Legends of Rock', '360', 'Activision', 2007, 'GuitarHero3.jpg');
INSERT INTO games VALUES ('Guitar Hero World Tour', '360', 'Activision', 2008, 'GuitarHeroTour.jpg');
INSERT INTO games VALUES ('Halo: Reach', '360', 'Bungie', 2010, 'HaloReach.jpg');
INSERT INTO games VALUES ('Hunted: The Demon''s Forge', '360', 'Bethesda Softworks', 2011, 'HuntedDemonForge.jpg');
INSERT INTO games VALUES ('Kameo Elements of Power', '360', 'Rare', 2005, 'Kameo.jpg');
INSERT INTO games VALUES ('Lost Planet: Extreme Condition', '360', 'Capcom', 2006, 'LostPlanet.jpg');
INSERT INTO games VALUES ('Metal Gear Rising: Revengeance', '360', 'Konami', 2013, 'MetalGearRising.jpg');
INSERT INTO games VALUES ('Mortal Kombat', '360', 'NetherRealm Studios', 2011, 'MortalKombat9.jpg');
INSERT INTO games VALUES ('Perfect Dark Zero', '360', 'Rare', 2005, 'PerfectDarkZero.jpg');
INSERT INTO games VALUES ('PocketBike Racer', '360', 'Burger King', 2006, 'PocketBikeRacer.jpg');
INSERT INTO games VALUES ('Quake 4', '360', 'id Software', 2005, 'Quake4.jpg');
INSERT INTO games VALUES ('Shadowrun', '360', 'FASA Studio', 2007, 'Shadowrun.jpg');
INSERT INTO games VALUES ('Warhammer 40,000: Space Marine', '360', 'THQ', 2011, 'SpaceMarine.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Ghost Recon Advanced Warfighter 2', '360', 'Ubisoft', 2007, 'AdvancedWarfighter2.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Splinter Cell: Conviction', '360', 'Ubisoft', 2010, 'SplinterCellConviction.jpg');
INSERT INTO games VALUES ('Tom Clancy''s Splinter Cell: Blacklist', '360', 'Ubisoft', 2013, 'SplinterCellBlacklist.jpg');
INSERT INTO games VALUES ('Turok', '360', 'Capcom', 2008, 'Turok360.jpg');
INSERT INTO games VALUES ('UFC 2009 Undisputed', '360', 'THQ', 2009, 'UFC2009.jpg');
INSERT INTO games VALUES ('Unreal Tournament 3', '360', 'Epic Games', 2007, 'UnrealTournament3.jpg');
INSERT INTO games VALUES ('The Witcher 2: Assassins of Kings Enhanced Edition', '360', 'CD Projekt RED', 2011, 'Witcher2.jpg');

--NINTENDO 3DS GAMES
INSERT INTO games VALUES ('The Legend of Zelda: A Link Between Worlds', '3DS', 'Nintendo', 2013, 'LinkBetweenWorlds.jpg');
INSERT INTO games VALUES ('Paper Mario: Sticker Star', '3DS', 'Nintendo', 2012, 'StickerStar.jpg');
INSERT INTO games VALUES ('Tales of the Abyss', '3DS', 'Bandai Namco', 2012, 'TalesOfTheAbyss.jpg');
INSERT INTO games VALUES ('Professor Layton and the Miracle Mask', '3DS', 'Level-5', 2011, 'MiracleMask.jpg');
INSERT INTO games VALUES ('Disney Epic Mickey: Power of Illusion', '3DS', 'Disney Interactive', 2012, 'PowerOfIllusion.jpg');

--PLAYSTATION VITA GAMES
INSERT INTO games VALUES ('Sly Cooper: Thieves in Time', 'Vita', 'Sanzaru Games', 2013, 'SlyCooperVita.jpg');

--WII U Games
INSERT INTO games VALUES ('Rayman Legends', 'Wii U', 'Ubisoft', 2013, 'RaymanLegends.jpg');
INSERT INTO games VALUES ('Super Smash Bros. for Wii U', 'Wii U', 'Nintendo', 2014, 'SmashWiiU.jpg');
INSERT INTO games VALUES ('Bayonetta 2', 'Wii U', 'Platinum Games', 2014, 'Bayonetta2.jpg');
INSERT INTO games VALUES ('Shovel Knight', 'Wii U', 'Yacht Club Games', 2014, 'ShovelKnight.jpg');
INSERT INTO games VALUES ('Hyrule Warriors', 'Wii U', 'Nintendo', 2014, 'HyruleWarriors.jpg');
INSERT INTO games VALUES ('Pikmin 3', 'Wii U', 'Nintendo', 2013, 'Pikmin3.jpg');
INSERT INTO games VALUES ('Donkey Kong Country: Tropical Freeze', 'Wii U', 'Nintendo', 2014, 'TropicalFreeze.jpg');
INSERT INTO games VALUES ('The Wonderful 101', 'Wii U', 'Platinum Games', 2013, 'Wonderful101.jpg');
INSERT INTO games VALUES ('Sonic Lost World', 'Wii U', 'Sega', 2013, 'SonicLostWorld.jpg');

--PLAYSTATION 4 GAMES
INSERT INTO games VALUES ('Vikings: Wolves of Midgard', 'PS4', 'Games Farm', 2017, 'WolvesOfMidgard.jpg');
INSERT INTO games VALUES ('Middle-Earth: Shadow of Mordor', 'PS4', 'Warner Bros. Interactive Entertainment', 2014, 'ShadowOfMordor.jpg');
INSERT INTO games VALUES ('Destiny', 'PS4', 'Bungie', 2014, 'Destiny.jpg');
INSERT INTO games VALUES ('Nioh', 'PS4', 'Team Ninja', 2017, 'Nioh.jpg');
INSERT INTO games VALUES ('The Last Guardian', 'PS4', 'Sony Interactive Entertainment', 2016, 'LastGuardian.jpg');
INSERT INTO games VALUES ('Final Fantasy XV', 'PS4', 'Square Enix', 2016, 'FFXV.jpg');
INSERT INTO games VALUES ('Deadpool', 'PS4', 'Activision', 2015, 'DeadpoolPS4.jpg');
INSERT INTO games VALUES ('Tomb Raider: Definitive Edition', 'PS4', 'Square Enix', 2013, 'TombRaiderDefinitive.jpg');
INSERT INTO games VALUES ('Diablo III: Ultimate Evil Edition', 'PS4', 'Blizzard Entertainment', 2014, 'Diablo3.jpg');
INSERT INTO games VALUES ('Alien: Isolation', 'PS4', 'Sega', 2014, 'AlienIsolation.jpg');
INSERT INTO games VALUES ('Watch Dogs', 'PS4', 'Ubisoft', 2014, 'WatchDogs.jpg');
INSERT INTO games VALUES ('Killzone Shadow Fall', 'PS4', 'Sony Computer Entertainment', 2013, 'Killzone.jpg');
INSERT INTO games VALUES ('Deus Ex: Mankind Divided', 'PS4', 'Square Enix', 2016, 'MankindDivided.jpg');
INSERT INTO games VALUES ('The Witcher 3: Wild Hunt', 'PS4', 'CD Projekt RED', 2015, 'WildHunt.jpg');
INSERT INTO games VALUES ('The Witcher 3: Wild Hunt - Blood and Wine', 'PS4', 'CD Projekt RED', 2016, 'BloodAndWine.jpg');
INSERT INTO games VALUES ('The Witcher 3: Wild Hunt - Hearts of Stone', 'PS4', 'CD Projekt RED', 2015, 'HeartsOfStone.jpg');
INSERT INTO games VALUES ('Metal Gear Solid V: The Phantom Pain', 'PS4', 'Konami', 2015, 'PhantomPain.jpg');
INSERT INTO games VALUES ('Metal Gear Solid V: Ground Zeroes', 'PS4', 'Konami', 2014, 'GroundZeroes.jpg');
INSERT INTO games VALUES ('Fallout 4', 'PS4', 'Bethesda Softworks', 2015, 'Fallout4.jpg');
INSERT INTO games VALUES ('Tom Clancy''s The Division', 'PS4', 'Ubisoft', 2016, 'TheDivision.jpg');
INSERT INTO games VALUES ('Assassin''s Creed Syndicate', 'PS4', 'Ubisoft', 2015, 'Syndicate.jpg');
INSERT INTO games VALUES ('Until Dawn', 'PS4', 'Sony Computer Entertainment', 2015, 'UntilDawn.jpg');
INSERT INTO games VALUES ('Metro Redux', 'PS4', 'THQ', 2014, 'MetroRedux.jpg');
INSERT INTO games VALUES ('Evolve', 'PS4', '2K Games', 2015, 'Evolve.jpg');
INSERT INTO games VALUES ('Wolfenstein: The New Order', 'PS4', 'Bethesda Softworks', 2014, 'TheNewOrder.jpg');
INSERT INTO games VALUES ('Skylanders: Swap Force', 'PS4', 'Activision', 2013, 'SwapForce.jpg');
INSERT INTO games VALUES ('Mortal Kombat X', 'PS4', 'NetherRealm Studios', 2015, 'MortalKombatX.jpg');
INSERT INTO games VALUES ('Sleeping Dogs: Definitive Edition', 'PS4', 'Square Enix', 2014, 'SleepingDogs.jpg');
INSERT INTO games VALUES ('The Elder Scrolls Online: Tamriel Unlimited', 'PS4', 'Bethesda Softworks', 2015, 'ElderScrollsOnline.jpg');
INSERT INTO games VALUES ('Far Cry 4', 'PS4', 'Ubisoft', 2014, 'FarCry4.jpg');
INSERT INTO games VALUES ('Dragon Age: Inquisition', 'PS4', 'Electronic Arts', 2014, 'Inquisition.jpg');
INSERT INTO games VALUES ('Assassin''s Creed Unity', 'PS4', 'Ubisoft', 2014, 'Unity.jpg');

--XBOX ONE GAMES
INSERT INTO games VALUES ('Dishonored 2', 'XBOne', 'Bethesda Softworks', 2016, 'Dishonored2.jpg');
INSERT INTO games VALUES ('Gears of War 4', 'XBOne', 'Microsoft Studios', 2016, 'GoW4.jpg');
INSERT INTO games VALUES ('Sunset Overdrive', 'XBOne', 'Microsoft Studios', 2014, 'SunsetOverdrive.jpg');
INSERT INTO games VALUES ('Batman: Arkham Knight', 'XBOne', 'Rocksteady Studios', 2015, 'ArkhamKnight.jpg');
INSERT INTO games VALUES ('Halo 5: Guardians', 'XBOne', '343 Industries', 2015, 'Halo5.jpg');
INSERT INTO games VALUES ('Far Cry Primal', 'XBOne', 'Ubisoft', 2016, 'FarCryPrimal.jpg');
INSERT INTO games VALUES ('Doom', 'XBOne', 'Bethesda Softworks', 2016, 'DoomOne.jpg');